### ISSUE TITLE
npm start tmp/lib/server

### ISSUE THREAD

**Issue by negati-ve** [imbhargav5/react-universal-starter#44]
npm start fails with following error:

```
> cross-env NODE_ENV=production node tmp/lib/server

module.js:544
    throw err;
    ^

Cannot find module 'users/n/react-universal-starter/tmp/lib/server'
```

Is this some missing code?

**Comment by imbhargav5** [comment]
Hey, thanks for pointing this out. Can you send a PR with the fix in the readme ? I will be happy to add you as a contributor.

**Comment by imbhargav5** [comment]
#46
