### ISSUE TITLE
npm run build:client

### ISSUE THREAD

**Issue by negati-ve** [imbhargav5/react-universal-starter#45]
what is this build script for?

when I run it and go to localhost:8080 I get
'Cannot GET /' 

I assume this is supposed to run the client side only using webpack dev server without express based server side rending ?

what is the expected behaviour?

**Comment by negati-ve** [comment]
got it.. build:client builds client separately and build:server builds server separately 
and run build runs both.

**Comment by imbhargav5** [comment]
Hey, sorry couldn't reply sooner. And thanks for the PR!
