### ISSUE TITLE
Build Production Mode

### ISSUE THREAD

**Issue by suryakencana007** [imbhargav5/react-universal-starter#50]
Built Production Mode got dead code elimination from react-tools extension
![screen shot 2017-12-28 at 5 35 54 pm](https://user-images.githubusercontent.com/4660505/34408327-d182ea5a-ebf5-11e7-9225-ba04316d3279.png)

**Comment by imbhargav5** [comment]
Thanks for creating the issue! Would you like to submit a PR ?
